### ISSUE TITLE
error TS2403: Subsequent variable declarations must have the same type.

### ISSUE THREAD

**Issue by ghost** [brianzinn/create-react-app-typescript-babylonjs#2]
I've just clone the site, and did "yarn install" and I get the following error:

E:\Files\playground\babylonjs-site\node_modules\@types\react-dom\node_modules\@types\react\index.d.ts
(3636,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.

I also tried to start with a fresh "create-react-app" and adding babylonjs, but I get a similar error:
E:/Files/playground/babylon-starter/node_modules/babylonjs/babylon.d.ts
(299,5): All declarations of 'hasOrientation' must have identical modifiers.

Note: I also tried doing with "NPM Install"

Any ideas why this could be happening.

**Comment by brianzinn** [comment]
Sorry about the late reply.  Let me know which version of BabylonJS you are using and I will do a clean install.  I recall some versions of BabylonJS had issues with typings.  The first error looks weird as the types match.  I've used both yarn and npm, so should work with both.
