### ISSUE TITLE
npm start fails to compile

### ISSUE THREAD

**Issue by dannysemi** [brianzinn/create-react-app-typescript-babylonjs#3]
```
Failed to compile.

./node_modules/react-babylonjs/dist/react-babylonjs.js
Module not found: Can't resolve '@react-spring/animated' in 'C:\Users\******\Documents\ReactBabylonjsTest\node_modules\react-babylonjs\dist'
```

Steps to reproduce:
1. Clone repo
2. npm install
3. npm start

**Comment by brianzinn** [comment]
Thank-you for reporting @dannysemi.  I think the project itself has taken too many dependencies - I was hoping as a peer dependency it wouldn't be required.  Drop down to `2.0.6` and I will split off the react-spring into a separate NPM.
```bash
yarn add react-babylonjs@2.0.6
```

**Comment by dannysemi** [comment]
Works great out of the box now. Thanks!
