### ISSUE TITLE
diffuseTexture

### ISSUE THREAD

**Issue by JRobsonGomes** [brianzinn/create-react-app-typescript-babylonjs#6]
Hi, could you help me.
I'm new to Babylonjs.
I would like to know how to add diffuseTexture to the material.

`<standardMaterial name='material1' specularPower={16}
                diffuseColor={Color3.Black()}
                emissiveColor={new Color3(0.5, 0.5, 0.5)}
                reflectionFresnelParameters={FresnelParameters.Parse({
                    isEnabled: true,
                    leftColor: [1, 1, 1],
                    rightColor: [0, 0, 0],
                    bias: 0.1,
                    power: 1
                })} diffuseTexture = {????}
              />`

https://github.com/brianzinn/create-react-app-typescript-babylonjs/blob/141ede2e33a88e9c112f9a0dcc1bc292223b4dad/src/App.tsx

**Comment by brianzinn** [comment]
hi @JRobsonGomes,
The easiest way is to create a child texture to the material.  The reason for `assignTo` is that we could assign to different properties such as `emissiveTexture` or `bumpTexture`.
```jsx
<standardMaterial name='example1' ... >
    <customProceduralTexture assignTo='diffuseTexture'/>
</standardMaterial>
```

That will work for all textures types.  If you are re-using a texture across materials then you can re-use the same instance like this:
```jsx
<standardMaterial name='example2' backFaceCulling={false}>
      <texture fromInstance={yourInstanceHere} assignTo="diffuseTexture" hasAlpha={true} />
</standardMaterial>
```
Let me know if you need more help with that - if you are using a regular path then you can just supply that.  There is an example storybook with source code up:
* [live demo](https://brianzinn.github.io/react-babylonjs/?path=/story/textures--image-texture)
* [source code](https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Textures/image-texture.stories.js)

**Comment by JRobsonGomes** [comment]
Yes, it helped me a lot.
Thank you very much @brianzinn.
Sorry for opening a problem, in fact I just wanted to comment.

**Comment by brianzinn** [comment]
no worries - feel free to open up issues in main repo, even with questions.  the documentation is not very good, so these kinds of questions are expected.  cheers.
