### ISSUE TITLE
Specify cannon dependency

### ISSUE THREAD

**Issue by wyhinton** [brianzinn/create-react-app-typescript-babylonjs#8]
As is, it seems like the project won't compile correctly without adding cannon as a dependency. Maybe this step should be added to the .readme?
```
yarn add react-babylonjs
yarn add @babylonjs/core
yarn add @babylonjs/gui
# loaders are optional
yarn add @babylonjs/loaders
yarn add cannon
```

**Comment by brianzinn** [comment]
@wyhinton that's a good point.  I guess I was explaining more in general - I'll put that in the docs along with `@types/cannon@types/cannon` for people using physics using that particular engine.
